config/routes.rb
Rails.application.routes.draw do
  resources :sponsors
  #devise_for :users, path: 'users'
  devise_for :users, controllers: {:registrations => "users/registrations"}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'pages#index', as: 'home'

  get 'search', to: 'player_profiles#search'

  resources :registration_steps

  resources :player_profiles
  resources :manager_profiles

  get '/check', :controller=>'sponsors', :action=>'checksponsorability'
  post '/validate', :controller=>'sponsors', :action=>'issponsorable'

  
  #get 'player_profiles', to: 'player_profiles#show'
  #get "player_profiles/:id" => "player_profiles#show"
  #get "projects/:category_id" => "projects#index"
end

app/models/manager_profile.rb
class ManagerProfile < ApplicationRecord
  belongs_to :user
  belongs_to :country, :foreign_key => "country_id"
  has_many :player_profile
end

app/controllers/manager_profiles_controller.rb
class ManagerProfilesController < ApplicationController
    
    before_action :authenticate_user!, only: [:new, :edit, :update, :destroy]

    def show
        @manager_profile = ManagerProfile.find(params[:id])
    end
    
    def new
        @manager_profile = ManagerProfile.new
    end

    def create
        @manager_profile = ManagerProfile.new(manager_profile_params)
        @manager_profile.save
        redirect_to @manager_profile

        #if @manager_profile.save
            #redirect_to edit_manager_profiles_path(@manager_profile), notice: 'Team Profile successfully registered.'
        #else
            #render :new
        #end
    end

    def edit
        @manager_profile = ManagerProfile.find(params[:id])
    end

    def update
        @manager_profile = ManagerProfile.find(params[:id])
        
        if @manager_profile.update(manager_profile_params)
            redirect_to @manager_profile, notice: "Team Profile successfully updated."
        else
            render 'edit'
        end

        #@manager_profile = ManagerProfile.find(params[:id])
        #@manager_profile.update(manager_profile_params)
        #redirect_to @manager_profile
    end

    def destroy
        @manager_profile.destroy
        redirect_to manager_profiles_url, notice: 'Team Profile was deleted.'
    end

    private
        def manager_profile_params
            params
                .require(:manager_profile)
                .permit(:user_id, :teamName, :description, :country_id, :managerFName, :managerLName, :sponsorsAndPartners, :twitterHandle, :siteUrl)
        end
end

app/helpers/manager_profile_helper.rb
module ManagerProfileHelper
end

app/views/manager_profiles/edit.html.erb
<%= form_for :manager_profile, url: manager_profile_path(@manager_profile), method: :patch do |f| %>
    <h2>Edit Team Details</h2>
    <div class="field">
        <%= f.label :teamName, 'Team Name' %><br />
        <%= f.text_field :teamName, class: "form-control" %>
    </div>

    <div class="field">
        <%= f.label :description, 'Team Bio' %><br />
        <%= f.text_area :description, class: "form-control" %>
    </div>

    <div class="field">
        <%= f.label :managerFName, 'Manager\'s First Name' %><br />
        <%= f.text_field :managerFName, class: "form-control" %>
    </div>

    <div class="field">
        <%= f.label :managerLName, 'Manager\'s Surname' %><br />
        <%= f.text_field :managerLName, class: "form-control" %>
    </div>

    <div class="field">
        <%= f.label :sponsorsAndPartners, 'Sponsors and Partners' %><br />
        <%= f.text_area :sponsorsAndPartners, class: "form-control" %>
    </div>

    <div class="field">
        <%= f.label :country_id, 'Founding Country'%><br />
        <% options = options_from_collection_for_select(Country.all, 'id', 'name') %>
        <%= f.select :country_id,  options %>
    </div>

    <div class="field">
        <%= f.label :twitterHandle, 'Twitter Handle' %><br />
        <%= f.text_field :twitterHandle, class: "form-control" %>
    </div>

    <div class="field">
        <%= f.label :siteUrl, 'Site URL' %><br />
        <%= f.text_field :siteUrl, class: "form-control" %>
    </div>

    <div class="actions">
        <%= f.submit %>
    </div>

    <% end %>

app/views/manager_profiles/new.html.erb
<%= form_for @manager_profile, url: manager_profiles_path(@manager_profile.id) do |f| %>
    <h2>Team Details</h2>
    <div class="field">
        <%= f.label :teamName, 'Team Name' %><br />
        <%= f.text_field :teamName %>
    </div>

    <div class="field">
        <%= f.label :description, 'Team Bio' %><br />
        <%= f.text_area :description %>
    </div>

    <div class="field">
        <%= f.label :managerFName, 'Manager\'s First Name' %><br />
        <%= f.text_field :managerFName %>
    </div>

    <div class="field">
        <%= f.label :managerLName, 'Manager\'s Surname' %><br />
        <%= f.text_field :managerLName %>
    </div>

    <div class="field">
        <%= f.label :sponsorsAndPartners, 'Sponsors and Partners' %><br />
        <%= f.text_area :sponsorsAndPartners %>
    </div>

    <div class="field">
        <%= f.label :country_id, 'Founding Country'%><br />
        <% options = options_from_collection_for_select(Country.all, 'id', 'name') %>
        <%= f.select :country_id,  options %>
    </div>

    <div class="field">
        <%= f.label :twitterHandle, 'Twitter Handle' %><br />
        <%= f.text_field :twitterHandle %>
    </div>

    <div class="field">
        <%= f.label :siteUrl, 'Site URL' %><br />
        <%= f.text_field :siteUrl %>
    </div>

    <%= f.hidden_field :user_id, value: current_user.id %>

    <div class="actions">
        <%= f.submit %>
    </div>

    <% end %>

app/views/manager_profiles/show.html.erb
<div class="container-fluid p-3">
    <div class="row border-bottom p-2">
        <div class="col-sm">
            <div class="row">
                <div class="col-sm">
                    <h1><%= @manager_profile.teamName %></h1>
                </div>
                <div class="col-sm text-right">
                    <% if @manager_profile.user_id == current_user.id %> 
                        <%= button_to "Edit Details", edit_manager_profile_path(@manager_profile), method: :get %>
                    <% end %>
                </div>
            </div>
            <div class="row">
                <div class="col-sm">
                    <p>Managed by: <%= @manager_profile.managerFName %> <%= @manager_profile.managerLName %></p>
                    <p>Founded in: <%= @manager_profile.country.name %></p>
                </div>
                <div class="col-sm text-right">
                    <p>Email: <%= @manager_profile.user.email %></p>
                    <p>Website: <%= @manager_profile.siteUrl %></p>
                </div>
            </div>
        </div>
    </div>
    <div class="row p-2">
        <div class="col-sm">
            <div class="card p-1">
                <h6>Description</h6>
                <div class="card p-1 overflow-auto" style="height: 450px;">
                    <%= @manager_profile.description %>
                </div>
            </div>
        </div>
        <div class="col-sm">
            <div class="card p-1">
                <h6>Sponsors and Partners</h6>
                <div class="card p-1 overflow-auto" style="height: 450px;">
                    <%= @manager_profile.sponsorsAndPartners %>
                </div>
            </div>
        </div>
    </div>
</div>