config/routes.rb
Rails.application.routes.draw do
  resources :sponsors
  #devise_for :users, path: 'users'
  devise_for :users, controllers: {:registrations => "users/registrations"}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'pages#index', as: 'home'

  get 'search', to: 'player_profiles#search'

  resources :registration_steps

  resources :player_profiles
  resources :manager_profiles

  get '/check', :controller=>'sponsors', :action=>'checksponsorability'
  post '/validate', :controller=>'sponsors', :action=>'issponsorable'

  
  #get 'player_profiles', to: 'player_profiles#show'
  #get "player_profiles/:id" => "player_profiles#show"
  #get "projects/:category_id" => "projects#index"
end

app/models/sponsor.rb
class Sponsor < ApplicationRecord
end

app/controllers/sponsors_controller.rb
class SponsorsController < ApplicationController
  before_action :set_sponsor, only: [:show, :edit, :update, :destroy]

  # GET /sponsors
  # GET /sponsors.json
  def index
    @sponsors = Sponsor.all
  end

  def issponsorable
    @input1 = params[:placings]
    @input2 = params[:participants]
    @input3 = params[:tournaments]
    @input4 = params[:streamHours]
    @input5 = params[:minutesOfVideo]
    @result = Sponsorability.runcheck(@input1.to_i, @input2.to_i, @input3.to_i, @input4.to_i, @input5.to_i)
  end

  # GET /sponsors/1
  # GET /sponsors/1.json
  def show
  end

  # GET /sponsors/new
  def new
    @sponsor = Sponsor.new
  end

  # GET /sponsors/1/edit
  def edit
  end

  # POST /sponsors
  # POST /sponsors.json
  def create
    @sponsor = Sponsor.new(sponsor_params)

    respond_to do |format|
      if @sponsor.save
        format.html { redirect_to @sponsor, notice: 'Sponsor was successfully created.' }
        format.json { render :show, status: :created, location: @sponsor }
      else
        format.html { render :new }
        format.json { render json: @sponsor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sponsors/1
  # PATCH/PUT /sponsors/1.json
  def update
    respond_to do |format|
      if @sponsor.update(sponsor_params)
        format.html { redirect_to @sponsor, notice: 'Sponsor was successfully updated.' }
        format.json { render :show, status: :ok, location: @sponsor }
      else
        format.html { render :edit }
        format.json { render json: @sponsor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sponsors/1
  # DELETE /sponsors/1.json
  def destroy
    @sponsor.destroy
    respond_to do |format|
      format.html { redirect_to sponsors_url, notice: 'Sponsor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sponsor
      @sponsor = Sponsor.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def sponsor_params
      params.require(:sponsor).permit(:placings, :participants, :tournaments, :streamHours, :minutesOfVideo)
    end
end

app/helpers/sponsors_helper.rb
module SponsorsHelper
end

app/views/sponsors/_checksponsorability.html.erb
<h3>Score how sponsorable you are!</h3>
    <p>You have to put in a lot of work to become part of a team; Let's see how you're doing!</p>
        
    <p>All values to be taken from the past 60 days</p>

    <%= form_tag "/validate" do %>
            
        Sum value of all tournament placings eg. 1st and 2nd would be 1+2<br />
        <%= text_field_tag :placings %><br/><br/>

        'Sum value of entrants in tournaments you have entered'<br />
        <%= text_field_tag :participants %><br/><br/>
        
        Number of tournaments you have entered<br />
        <%= text_field_tag :tournaments %><br/><br/>

        Number of hours you have spent streaming<br />
        <%= text_field_tag :streamHours %><br/><br/>

        Number of minutes uploaded in total to YouTube (can include stream highlights but not VOD uploads)<br />
        <%= text_field_tag :minutesOfVideo %><br/><br/>


        <%= submit_tag "Calculate Your Score" %>
    <% end %>

app/views/sponsors/_form.html.erb
<%= form_with(model: sponsor, local: true) do |form| %>
  <% if sponsor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sponsor.errors.count, "error") %> prohibited this sponsor from being saved:</h2>

      <ul>
        <% sponsor.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :placings %>
    <%= form.text_field :placings %>
  </div>

  <div class="field">
    <%= form.label :participants %>
    <%= form.text_field :participants %>
  </div>

  <div class="field">
    <%= form.label :tournaments %>
    <%= form.text_field :tournaments %>
  </div>

  <div class="field">
    <%= form.label :streamHours %>
    <%= form.text_field :streamHours %>
  </div>

  <div class="field">
    <%= form.label :minutesOfVideo %>
    <%= form.number_field :minutesOfVideo %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/sponsors/edit.html.erb
<h1>Editing Sponsor</h1>

<%= render 'form', sponsor: @sponsor %>

<%= link_to 'Show', @sponsor %> |
<%= link_to 'Back', sponsors_path %>

app/views/sponsors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sponsors</h1>

<table>
  <thead>
    <tr>
      <th>Placings</th>
      <th>Participants</th>
      <th>Tournaments</th>
      <th>Streamhours</th>
      <th>Minutesofvideo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sponsors.each do |sponsor| %>
      <tr>
        <td><%= sponsor.placings %></td>
        <td><%= sponsor.participants %></td>
        <td><%= sponsor.tournaments %></td>
        <td><%= sponsor.streamHours %></td>
        <td><%= sponsor.minutesOfVideo %></td>
        <td><%= link_to 'Show', sponsor %></td>
        <td><%= link_to 'Edit', edit_sponsor_path(sponsor) %></td>
        <td><%= link_to 'Destroy', sponsor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sponsor', new_sponsor_path %>

app/views/sponsors/issponsorable.html.erb
<%= @result.html_safe %>

app/views/sponsors/new.html.erb
<h1>New Sponsor</h1>

<%= render 'form', sponsor: @sponsor %>

<%= link_to 'Back', sponsors_path %>

app/views/sponsors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Placings:</strong>
  <%= @sponsor.placings %>
</p>

<p>
  <strong>Participants:</strong>
  <%= @sponsor.participants %>
</p>

<p>
  <strong>Tournaments:</strong>
  <%= @sponsor.tournaments %>
</p>

<p>
  <strong>Streamhours:</strong>
  <%= @sponsor.streamHours %>
</p>

<p>
  <strong>Minutesofvideo:</strong>
  <%= @sponsor.minutesOfVideo %>
</p>

<%= link_to 'Edit', edit_sponsor_path(@sponsor) %> |
<%= link_to 'Back', sponsors_path %>