config/routes.rb
Rails.application.routes.draw do
  resources :sponsors
  #devise_for :users, path: 'users'
  devise_for :users, controllers: {:registrations => "users/registrations"}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'pages#index', as: 'home'

  get 'search', to: 'player_profiles#search'

  resources :registration_steps

  resources :player_profiles
  resources :manager_profiles

  get '/check', :controller=>'sponsors', :action=>'checksponsorability'
  post '/validate', :controller=>'sponsors', :action=>'issponsorable'

  
  #get 'player_profiles', to: 'player_profiles#show'
  #get "player_profiles/:id" => "player_profiles#show"
  #get "projects/:category_id" => "projects#index"
end

app/models/player_profile.rb
class PlayerProfile < ApplicationRecord
  belongs_to :user
  belongs_to :country, :foreign_key => "country_id"
  belongs_to :manager_profile, :foreign_key => "manager_profile_id", required: false
end

app/controllers/player_profiles_controller.rb
require 'twitter'

class PlayerProfilesController < ApplicationController

    before_action :authenticate_user!, only: [:new, :edit, :update, :destroy]

    def search
        @player_profile = PlayerProfile.where('playerTag LIKE ?', '%' + params[:q] + '%' )
    end

    #def manage
        #@manage_player_profile = PlayerProfile.where('manager_profile_id LIKE ?', current_user.manager_profile.id)


        #@client = Twitter::REST::Client.new do |config|
            #config.consumer_key        = "NoSQIiHJUVYg5VseZAWEhUBrS"
            #config.consumer_secret     = "XVoumcEH0f21M9JZKkpKaJX7P6vdZcP8eO6v4NfjC9e9NoQV9V"
            #config.access_token        = "513730483-5oRBjvhWcgyvPNyOUFtrCie0IC9BTVBKwG9AlQhS"
            #config.access_token_secret = "sbRzMKNePlj3OlSINQDZJQVxBhFViHHuTAt59jId6few6"
        #end
    #end
    
    def show
        @player_profile = PlayerProfile.find(params[:id])

        @client = Twitter::REST::Client.new do |config|
            config.consumer_key        = "NoSQIiHJUVYg5VseZAWEhUBrS"
            config.consumer_secret     = "XVoumcEH0f21M9JZKkpKaJX7P6vdZcP8eO6v4NfjC9e9NoQV9V"
            config.access_token        = "513730483-5oRBjvhWcgyvPNyOUFtrCie0IC9BTVBKwG9AlQhS"
            config.access_token_secret = "sbRzMKNePlj3OlSINQDZJQVxBhFViHHuTAt59jId6few6"
        end
    end

    def new
        @player_profile = PlayerProfile.new
    end

    def create
        @player_profile = PlayerProfile.new(player_profile_params)
        @player_profile.save
        redirect_to @player_profile
    end

    def edit
        @player_profile = PlayerProfile.find(params[:id])
    end

    def update
        #if @player_profile.update(player_profile_params)
            #redirect_to edit_player_profiles_path(@player_profile), notice: "Player Profile successfully updated."
        #else
            #render :edit
        #end

        @player_profile = PlayerProfile.find(params[:id])
        
        if @player_profile.update(player_profile_params)
            redirect_to @player_profile, notice: "Player Profile successfully updated."
        else
            render 'edit'
        end

        #@player_profile = PlayerProfile.find(params[:id])
        #@player_profile.update(player_profile_params)
        #redirect_to @player_profile

    end

    def destroy
        @player_profile.destroy
        redirect_to player_profiles_url, notice: 'Player Profile was deleted.'
    end

    private
        #def set_player_profile
            #@player_profile = PlayerProfile.find(params[:id])
        #end

        def player_profile_params
            params
                .require(:player_profile)
                .permit(:user_id, :playerTag, :bio, :firstName, :lastName, :dob, :country_id, :twitterHandle, :twitchHandle, :manager_profile_id, :hasSponsor)
        end
end

app/helpers/player_profile_helper.rb
module PlayerProfileHelper
end

app/views/player_profiles/_manage.html.erb
<% require 'twitter' %>

<div class="border-bottom float-none">
    <h1>Welcome back to The Big Leagues!</h1>
</div>

<% PlayerProfile.where('manager_profile_id LIKE ?', current_user.manager_profile.id).each do |player| %>
  <div class="border row">
    <div class="column w-50">
        <% @player_profile = player %>
        <h3><%= @player_profile.playerTag %></br></h3>
        <p><%= @player_profile.firstName %> <%= player.lastName %></p>
    </div>
    <div class="column w-50">
        <%= render 'player_profiles/tweets' %>
    </div>
  </div>
<% end %>

app/views/player_profiles/_manage_or_edit_button.html.erb
<% if user_signed_in? %>
    <% if current_user.managerCheck == true %>
        <% if @player_profile.hasSponsor == true && @player_profile.manager_profile.user_id != current_user.id %>
            <h5>This player is already part of a team</h5>
        <% elsif @player_profile.hasSponsor == true && @player_profile.manager_profile.user_id == current_user.id %>
            <%= form_for @player_profile, url: player_profile_path(@player_profile), method: :patch do |f| %>
                    
                <%= f.hidden_field :manager_profile_id, value: nil %>

                <%= f.hidden_field :hasSponsor, value: false %>
                
                <div class="actions">
                    <%= f.submit "Remove Player" %>
                </div>
            <% end %>
        <% else %>
            <%= form_for @player_profile, url: player_profile_path(@player_profile), method: :patch do |f| %>
                <%= f.hidden_field :manager_profile_id, value: current_user.manager_profile.id %>

                <%= f.hidden_field :hasSponsor, value: true %>
                
                <div class="actions">
                    <%= f.submit "Add Player" %>
                </div>
            <% end %>
        <% end %>
    <% elsif @player_profile.user_id == current_user.id %> 
        <%= button_to "Edit Profile", edit_player_profile_path(@player_profile), method: :get %>
    <% end %>
<% end %>

app/views/player_profiles/_manage_player_profile.html.erb
<div class="border row">
    <div class="column w-50">
        <h3><%= @players.playerTag %></br></h3>
        <p><%= @players.firstName %> <%= @players.lastName %></p>
    </div>
    <div class="column w-50">
        <%= render 'player_profiles/tweets' %>
    </div>
</div>

app/views/player_profiles/_player_home.html.erb
<div class="row p-2 border-bottom">
    <div class="col-sm">
        <h1>Welcome back to The Big Leagues!</h1>
    </div>
</div>
<div class="row p-2">
    <div class="col-sm">
        <%= render 'sponsors/checksponsorability' %>
    </div>
</div>

app/views/player_profiles/_player_profile.html.erb
<div class="border">
    <h3><%= player_profile.playerTag %></br></h3>
    <p><%= player_profile.firstName %> <%= player_profile.lastName %></p>
    <p><%= player_profile.country.name %></p>
    <%= link_to "View Profile", player_profile_path(player_profile) %>
</div>

app/views/player_profiles/_tweets.html.erb
<div class="card p-2" style="height: 460px;">
    <h3>Most recent tweets: </h3>
    <% begin %>
        <div class="card p-2 overflow-auto">
            <% @client.user_timeline(@player_profile.twitterHandle, tweet_mode: 'extended').take(30).collect do |tweet| %>
                <div class="card p-1"> 
                    <p><%= image_tag("#{tweet.user.profile_image_url_https}", style: 'height:25px;width:25px;') %> <%= "#{tweet.user.screen_name}" %>:</p>
                    <p><%= "#{tweet.text}" %> </p>
                </div>
            <% end %>
    <% rescue %>
        <p>Provided account is invalid!</p>
    <% end %>
    </div>
</div>

app/views/player_profiles/edit.html.erb
<%= form_for :player_profile, url: player_profile_path(@player_profile), method: :patch do |f| %>
    <h2>Edit Profile Details</h2>
    <div class="field">
        <%= f.label :playerTag, 'Player Tag' %><br />
        <%= f.text_field :playerTag, class: "form-control" %>
    </div>

    <div class="field">
        <%= f.label :firstName, 'First Name' %><br />
        <%= f.text_field :firstName, class: "form-control" %>
    </div>

    <div class="field">
        <%= f.label :lastName, 'Last Name' %><br />
        <%= f.text_field :lastName, class: "form-control" %>
    </div>

    <div class="field">
        <%= f.label :bio, 'Player Bio' %><br />
        <%= f.text_area :bio, class: "form-control" %>
    </div>

    <div class="field">
        <%= f.label :dob, 'Date of Birth' %><br />
        <%= f.date_select :dob, start_year: Time.now.year, end_year: 1900 %>
    </div>

    <div class="field">
        <%= f.label :country_id, 'Country of Residence' %><br />
        <% options = options_from_collection_for_select(Country.all, 'id', 'name') %>
        <%= f.select :country_id,  options, class: "form-control" %>
    </div>

    <div class="field">
        <%= f.label :twitterHandle, 'Twitter Handle' %><br />
        <%= f.text_field :twitterHandle, class: "form-control" %>
    </div>

    <div class="field">
        <%= f.label :twitchHandle, 'Twitch Handle' %><br />
        <%= f.text_field :twitchHandle, class: "form-control" %>
    </div>

    <br />
    <div class="actions">
        <%= f.submit({:class => 'btn btn-primary'}) %>
    </div>
<% end %>

app/views/player_profiles/index.html.erb
<div class="container p-3">
    <% if user_signed_in? %>
        <% if current_user.managerCheck == true %>
            <%= render 'player_profiles/manage' %>
        <% else %>
            <%= render 'player_profiles/player_home' %>
        <% end %>
    <% else %>
        <%= render 'unlogged' %>
    <% end %>
</div>

app/views/player_profiles/new.html.erb
<%= form_for @player_profile, url: player_profiles_path(@player_profile.id) do |f| %>
    <h2>Profile Details</h2>
    <div class="field">
        <%= f.label :playerTag, 'Player Tag' %><br />
        <%= f.text_field :playerTag, class: "form-control" %>
    </div>

    <div class="field">
        <%= f.label :firstName, 'First Name' %><br />
        <%= f.text_field :firstName, class: "form-control" %>
    </div>

    <div class="field">
        <%= f.label :lastName, 'Last Name' %><br />
        <%= f.text_field :lastName, class: "form-control" %>
    </div>

    <div class="field">
        <%= f.label :bio, 'Player Bio' %><br />
        <%= f.text_area :bio, class: "form-control" %>
    </div>

    <div class="field">
        <%= f.label :dob, 'Date of Birth' %><br />
        <%= f.date_select :dob, start_year: Time.now.year, end_year: 1900 %>
    </div>

    <div class="field">
        <%= f.label :country_id, 'Country of Residence' %><br />
        <% options = options_from_collection_for_select(Country.all, 'id', 'name') %>
        <%= f.select :country_id,  options, class: "form-control" %>
    </div>

    <div class="field">
        <%= f.label :twitterHandle, 'Twitter Handle' %><br />
        <%= f.text_field :twitterHandle, class: "form-control" %>
    </div>

    <div class="field">
        <%= f.label :twitchHandle, 'Twitch Handle' %><br />
        <%= f.text_field :twitchHandle, class: "form-control" %>
    </div>

    <%= f.hidden_field :user_id, value: current_user.id %>

    <br />
    <div class="actions">
        <%= f.submit({:class => 'btn btn-primary'}) %>
    </div>
<% end %>

app/views/player_profiles/search.html.erb
<h1>Search Results</h1>

<% if @player_profile.present? %>
  <%= render @player_profile %>
<% else %>
  <p>There are no posts containing the term(s).</p>
<% end %>

app/views/player_profiles/show.html.erb
<div class="container-fluid p-3">
    <div class="row border-bottom p-2">
        <div class="col-sm">
            <div class="row">
                <div class="col-sm">
                    <h1><%= @player_profile.playerTag %></h1>
                </div>
                <div class="col-sm text-right">
                    <%= render "manage_or_edit_button" %>
                </div>
            </div>
            <div class="row">
                <div class="col-sm">
                    <%= @player_profile.firstName %> <%= @player_profile.lastName %>
                </div>
                <div class="col-sm text-right">
                    <p>Email: <%= @player_profile.user.email %></p>
                </div>
            </div>
        </div>
    </div>
    <div class="row p-2">
        <div class="col-sm">
            <div class="card p-1">
                <h6>Bio</h6>
                <div class="card p-1">
                    <p>Date of Birth: <%= @player_profile.dob %></p>
                    <p class="text-capitalize"><%= @player_profile.country.name %></p>

                    <%= @player_profile.bio %>
                </div>
            </div>
        </div>
        <div class="col-sm">
            <p>Twitter: <a href="https://twitter.com/<%= @player_profile.twitterHandle %>"><%= @player_profile.twitterHandle %></a></p>
            <p>Twitch: <a href="https://twitch.tv/<%= @player_profile.twitchHandle %>"><%= @player_profile.twitchHandle %></a></p>

            <%= render 'tweets' %>
        </div>
    </div>
</div>